---
title: xml.parsers.expat.XML_ERROR_ENTITY_DECLARED_IN_PE
permalink: /Python/xml-parsers-expat/XML_ERROR_ENTITY_DECLARED_IN_PE/
date: 2021-01-01
key: Python.X.xml.parsers.expat.XML_ERROR_ENTITY_DECLARED_IN_PE
category: python
tags: ['constante python', 'xml-parsers-expat']
sidebar: 
  nav: python
---

## Descripción
{{site.data.Python.X.xmlparsersexpat.XML_ERROR_ENTITY_DECLARED_IN_PE.description }}

## Sintaxis
~~~python
{{ site.data.Python.X.xmlparsersexpat.XML_ERROR_ENTITY_DECLARED_IN_PE.sintaxis }}~~~

## Ejemplo
~~~python
{{ site.data.Python.X.xmlparsersexpat.XML_ERROR_ENTITY_DECLARED_IN_PE.code}}
~~~

## Artículos
<ul>
{%- for _ldc in site.data.Python.X.xmlparsersexpat.XML_ERROR_ENTITY_DECLARED_IN_PE.ldc -%}
   <li>
       <a href="{{_ldc['url'] }}">{{ _ldc['nombre'] }}</a>
   </li>
{%- endfor -%}
</ul>
