---
title: traceback.TracebackException.__context__
permalink: /Python/traceback/TracebackException/__context__/
date: 2021-01-01
key: Python.T.traceback.TracebackException.__context__
category: python
tags: ['atributo python', 'traceback']
sidebar: 
  nav: python
---

{% include w3api/datos.html clase=site.data.Python.T.traceback.TracebackException.atributos valor="__context__" %}

## Descripción
{{_dato.description }}

## Sintaxis
~~~python
{{ _dato.sintaxis }}~~~

## Clase Padre
[TracebackException](/Python/traceback/TracebackException/)

## Ejemplo
~~~python
{{ _dato.code}}
~~~

## Artículos
<ul>
{%- for _ldc in _dato.ldc -%}
   <li>
       <a href="{{_ldc['url'] }}">{{ _ldc['nombre'] }}</a>
   </li>
{%- endfor -%}
</ul>
