---
title: concurrent.futures.CancelledError
permalink: /Python/concurrent-futures/CancelledError/
date: 2021-01-01
key: Python.C.concurrent.futures.CancelledError
category: python
tags: ['excepcion python', 'concurrent-futures']
sidebar: 
  nav: python
---

## Descripción
{{site.data.Python.C.concurrentfutures.CancelledError.description }}

## Sintaxis
~~~python
{{ site.data.Python.C.concurrentfutures.CancelledError.sintaxis }}~~~

## Ejemplo
~~~python
{{ site.data.Python.C.concurrentfutures.CancelledError.code}}
~~~

## Artículos
<ul>
{%- for _ldc in site.data.Python.C.concurrentfutures.CancelledError.ldc -%}
   <li>
       <a href="{{_ldc['url'] }}">{{ _ldc['nombre'] }}</a>
   </li>
{%- endfor -%}
</ul>
